### ISSUE TITLE
Migrate auto-formatting tool to clang-format.

### ISSUE THREAD

**Issue by ArielMAJ** [ArielMAJ/test.me#125]
## TO-DO:

- [ ] Re-format test.me.c;
- [ ] Update README.md and CONTRIBUTING.md:
    - [ ] Explain how to install clang-format on dev-environment section;
    - [ ] Explain how to use clang-format;
    - [ ] Explain that it should be ran while editing files, especially before making PRs.

## How to install and use:
On windows: 
- Install llvm through [chocolatey](https://chocolatey.org/install#install-step2):
```sh
choco install llvm
```
- Run clang-format:
```
clang-format -i ./test.me.c
```
- [Optional] Install Clang-Format extension on vscode to facilitate formatting (or configure your IDE of choice).
